---
- include: mariadb_pip.yml

- include: mariadb_pkg.yml

- include: mariadb_config.yml

- include: mariadb_block.yml
  when:
    - enable_zfs == 'true' or enable_lvm == 'true'

- include: mariadb_zfs.yml
  when:
    - enable_zfs == 'true'

- include: mariadb_lvm.yml
  when:
    - enable_lvm == 'true'

- include: mariadb_mount.yml
  when:
    - enable_zfs == 'true' or enable_lvm == 'true'

- include: mariadb_secure.yml

- include: mariadb_k3s.yml
