---
- include: mariadb_pip.yml

- include: mariadb_pkg.yml

- include: mariadb_config.yml

- include: mariadb_block.yml
  when:
    - enable_zfs or enable_lvm

- include: mariadb_zfs.yml
  when:
    - enable_zfs

- include: mariadb_lvm.yml
  when:
    - enable_lvm

- include: mariadb_mount.yml
  when:
    - enable_zfs or enable_lvm

- include: mariadb_secure.yml

- include: mariadb_k3s.yml
