---
- name: Check MariaDB Root Password is set
  command: mysql -u root -e "quit"
  changed_when: false
  ignore_errors: true
  register: mariadb_root_init

- name: MariaDB Disable Root Plugin 'unix_socket'
  command: mysql -u root -e "UPDATE mysql.user SET plugin = '' WHERE user = 'root'; FLUSH PRIVILEGES;"
  when: mariadb_root_init.rc == 0

- name: MariaDB Disable Root Remote Login
  command: mysql -u root -e "DELETE FROM mysql.user WHERE user='root' AND host NOT IN ('localhost', '127.0.0.1', '::1');"
  when: mariadb_root_init.rc == 0

- name: MariaDB Update Root User
  mysql_user:
    login_user: root
    name: root
    password: "{{ mariadb_root_password }}"
    priv: "*.*:ALL,GRANT"
    host: "{{ item }}"
    state: present
  with_items:
    - "localhost"
    - "127.0.0.1"
    - "::1"
  when: mariadb_root_init.rc == 0

- name: MariaDB Remove Anonymous User
  mysql_user: 
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    user: ""
    host_all: yes
    state: absent

- name: MariaDB Remove Test Database
  mysql_db:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    name: test
    state: absent

- name: MariaDB Flush Priviliges
  command: mysql -u root -p{{ mariadb_root_password }} -e "FLUSH PRIVILEGES"
