---
- include: k3s-agent_block.yml
  when:
    - enable_zfs == 'true' or enable_lvm == 'true'

- include: k3s-agent_zfs.yml
  when:
    - enable_zfs == 'true'

- include: k3s-agent_lvm.yml
  when:
    - enable_lvm == 'true'

- include: k3s-agent_mount.yml
  when:
    - enable_zfs == 'true' or enable_lvm == 'true'

- include: k3s-agent_pkg.yml

- include: k3s-agent_mod.yml

- include: k3s-agent_sysctl.yml

- include: k3s-agent_svc.yml
