---
- hosts: balancer:database:masters:infras:nodes
  any_errors_fatal: true
  roles:
  - role: facts

- hosts: masters:infras:nodes
  any_errors_fatal: true
  roles:
  - role: common

- hosts: masters
  any_errors_fatal: true
  serial: 1
  roles:
    - role: k3s/master

- hosts: infras:nodes
  any_errors_fatal: true
  roles:
    - role: k3s/node
