---
- hosts: balancer:database:new_infras:new_nodes
  any_errors_fatal: true
  roles:
  - role: facts

- hosts: new_infras:new_nodes
  any_errors_fatal: true
  roles:
  - role: common

- hosts: new_infras:new_nodes
  any_errors_fatal: true
  roles:
    - role: k3s/node
