---
- name: Fail if Operating System is not Supported
  fail:
    msg: "Supported Operating System is Debian 64-bit"
  when:
    - ansible_distribution != 'Debian'
    - ansible_architecture != 'x86_64'

- name: Set Facts
  set_fact:
    node_ip: "{{ node_ip | default(default_value, true) }}"
    node_name: "{{ node_name | default(default_value, true) }}"
    k3s_channel: "{{ k3s_channel | default(default_value, true) }}"
    k3s_version: "{{ k3s_version | default(default_value, true) }}"
    server_san: "{{ server_san | default(default_value, true) }}"
    server_token: "{{ server_token | default(default_value, true) }}"
    db_host: "{{ db_host | default(default_value, true) }}"
    db_user: "{{ db_user | default(default_value, true) }}"
    db_password: "{{ db_password | default(default_value, true) }}"
    db_name: "{{ db_name | default(default_value, true) }}"
    disable_traefik: "{{ disable_traefik | default(default_value, true) }}"
    disable_servicelb: "{{ disable_servicelb | default(default_value, true) }}"
    disable_coredns: "{{ disable_coredns | default(default_value, true) }}"
    disable_metric_server: "{{ disable_metric_server | default(default_value, true) }}"
    disable_local_storage: "{{ disable_local_storage | default(default_value, true) }}"
    disable_flannel: "{{ disable_flannel | default(default_value, true) }}"
    pods_per_core: "{{ pods_per_core | default(default_value, true) }}"
    enable_ip_vs: "{{ enable_ip_vs | default(default_value, true) }}"
    ip_vs_mode: "{{ ip_vs_mode | default(default_value, true) }}"
    block_wipe: "{{ block_wipe if block_device is defined else 'false' | default(default_value, true) }}"
    enable_zfs: "{{ enable_zfs | default(default_value, true) }}"
    zfs_pool_name: "{{ zfs_pool_name | default(default_value, true) }}"
    zfs_pool_wipe: "{{ zfs_pool_wipe | default(default_value, true) }}"
    zfs_dataset_wipe: "{{ zfs_dataset_wipe | default(default_value, true) }}"
    enable_lvm: "{{ enable_lvm | default(default_value, true) }}"
    lvm_vg_name: "{{ lvm_vg_name | default(default_value, true) }}"

- name: Make Sure 'enable_lvm' is false When 'enable_zfs' is true
  set_fact:
    enable_lvm: 'false'
  when:
    - enable_zfs

- name: Make Sure 'enable_zfs' is false When 'enable_lvm' is true
  set_fact:
    enable_zfs: 'false'
  when:
    - enable_lvm
