---
# Default for Node IP
node_ip: "{{ ansible_default_ipv4.address }}"

# Default for Node Name
node_name: "{{ ansible_hostname }}"

# Default for Helm Version
helm_version: '3.15.2'

# Default for K3S Channel
k3s_channel: 'stable'

# Default for K3S Version
k3s_version: 'v1.28.8-k3s1'

# Default for K3S Server SAN
server_san: ''

# Default for K3S Server URL
server_url: "https://{{ hostvars[groups['masters'][0]]['node_ip'] }}:6443"

# Default for K3S Server Token
server_token: 'THIS_IS_YOUR_SERVER_TOKEN'

# Default for K3S Database Host
db_host: ''

# Default for K3S Database User
db_user: ''

# Default for K3S Database Password
db_password: ''

# Default for K3S Database Name
db_name: ''

# Default for K3S Disable Traefik
disable_traefik: 'false'

# Default for K3S Disable ServiceLB
disable_servicelb: 'false'

# Default for K3S Disable CoreDNS
disable_coredns: 'false'

# Default for K3S Disable Metric Server
disable_metric_server: 'false'

# Default for K3S Disable Local Storage
disable_local_storage: 'false'

# Default for K3S Disable Flannel
disable_flannel: 'false'

# Default for K3S Cluster CIDR
cluster_cidr: '172.30.0.0/16'

# Default for K3S Pods-per-Core
pods_per_core: 10

# Default for Enable IPVS
enable_ip_vs: 'false'

# Default for IPVS Mode
ip_vs_mode: 'lc'

# Default for Block Wipe
block_wipe: 'false'

# Default for Enable ZFS
enable_zfs: 'false'

# Default for ZFS Pool Name
zfs_pool_name: 'data'

# Default for ZFS Pool Wipe
zfs_pool_wipe: 'false'

# Default for ZFS Dataset Wipe
zfs_dataset_wipe: 'false'

# Default for Enable LVM
enable_lvm: 'false'

# Default for LVM Volume Group Name
lvm_vg_name: 'vg-data'
