---
- name: Create K3S Service File
  template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0644

- name: Reload SystemD to Load K3S Service File
  systemd:
    name: k3s
    daemon_reload: yes
    state: stopped

- name: Enabling and Restarting K3S Service
  service:
    name: k3s
    enabled: yes
    state: restarted
