---
- name: Create K3S Installer File from Template
  template:
    src: k3s-install.sh.j2
    dest: /tmp/k3s-install.sh
    owner: root
    group: root
    mode: 0755

- name: Running K3S Installer
  command: /tmp/k3s-install.sh

- name: Remove K3S Installer File
  file:
    path: /tmp/k3s-install.sh
    state: absent
