---
- name: Create Modules Load Needed By K3S from Template
  template:
    src: k3s.conf.j2
    dest: /etc/modules-load.d/k3s.conf
    owner: root
    group: root
    mode: 0644

- name: Load Needed Module By K3S to Kernel
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay
