---
- name: Fail if Operating System is not Supported
  fail:
    msg: "Supported Operating System is Debian"
  when:
    - ansible_distribution != 'Debian'

- name: Set Facts
  set_fact:
    node_ip: "{{ node_ip | default(default_value, true) }}"
    database_backend: "{{ database_backend | default(default_value, true) }}"
    mariadb_version: "{{ mariadb_version | default(default_value, true) }}"
    mariadb_root_password: "{{ mariadb_root_password | default(default_value, true) }}"
    db_user: "{{ db_user | default(default_value, true) }}"
    db_password: "{{ db_password | default(default_value, true) }}"
    db_name: "{{ db_name | default(default_value, true) }}"
    block_wipe: "{{ block_wipe if block_device is defined else 'false' | default(default_value, true) }}"
    enable_zfs: "{{ enable_zfs | default(default_value, true) }}"
    zfs_pool_name: "{{ zfs_pool_name | default(default_value, true) }}"
    zfs_pool_wipe: "{{ zfs_pool_wipe | default(default_value, true) }}"
    zfs_dataset_wipe: "{{ zfs_dataset_wipe | default(default_value, true) }}"
    enable_lvm: "{{ enable_lvm | default(default_value, true) }}"
    lvm_vg_name: "{{ lvm_vg_name | default(default_value, true) }}"

- name: Make Sure 'enable_lvm' is false When 'enable_zfs' is true
  set_fact:
    enable_lvm: 'false'
  when:
    - enable_zfs

- name: Make Sure 'enable_zfs' is false When 'enable_lvm' is true
  set_fact:
    enable_zfs: 'false'
  when:
    - enable_lvm
