---
- name: Install IPVS Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    state: present
  with_items:
    - ipvsadm

- name: Create Modules Load for IPVS from Template
  template:
    src: ip_vs.conf.j2
    dest: /etc/modules-load.d/ip_vs.conf
    owner: root
    group: root
    mode: 0644

- name: Load IPVS Module to Kernel
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_lc
    - ip_vs_dh
    - ip_vs_sh
    - ip_vs_sed
    - ip_vs_nq
