---
- name: Enable Backports Repository
  template:
    src: backports.list.j2
    dest: /etc/apt/sources.list.d/backports.list
    owner: root
    group: root
    mode: 0644

- name: Pin ZFS Packages to Use Backports Repository
  template:
    src: backports-zfs.j2
    dest: /etc/apt/preferences.d/backports-zfs
    owner: root
    group: root
    mode: 0644

- name: Install ZFS Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    state: present
  with_items:
    - zfs-dkms
    - zfsutils-linux

- name: Load ZFS Module to Kernel
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - zfs
