---
- name: Upgrade Operating System
  apt:
    force_apt_get: yes
    update_cache: yes
    dpkg_options: "force-confdef,force-confold"
    upgrade: full
  register: os_upgrade_info

- name: Restart Node If Operating System Upgraded
  shell: sleep 5 && shutdown -r now "Operating System Upgrade Triggered" 
  args:
    warn: false
  async: 1
  poll: 0    
  when: os_upgrade_info.changed

- name: Wait For Node to Be Ready If Operating System Upgraded
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 600
  when: os_upgrade_info.changed

- name: Install Base Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    state: present
  with_items:
    - bash-completion
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - gnupg
    - lsb-release
    - curl
    - wget
    - rsync
    - byobu
