---
- name: Fail if Operating System is not Supported
  fail:
    msg: "Supported Operating System is Debian"
  when:
    - ansible_distribution != 'Debian'

- name: Set Facts
  set_fact:
    node_ip: "{{ node_ip | default(default_value, true) }}"
