---
- name: Pin HAProxy Packages to Use Backports Repository
  template:
    src: backports-haproxy.j2
    dest: /etc/apt/preferences.d/backports-haproxy
    owner: root
    group: root
    mode: 0644

- name: Install HAProxy Packages
  apt:
    name: "{{ item }}"
    default_release: "{{ ansible_distribution_release }}-backports"
    force_apt_get: yes
    update_cache: yes
    state: present
  with_items:
    - haproxy
