---
- name: Fail if Operating System is not Supported
  fail:
    msg: "Supported Operating System is Debian"
  when:
    - ansible_distribution != 'Debian'

- name: Set Facts
  set_fact:
    reboot_upgrade: "{{ reboot_upgrade | default(default_value, true) }}"
    enable_ip_vs: "{{ enable_ip_vs | default(default_value, true) }}"
    enable_zfs: "{{ enable_zfs | default(default_value, true) }}"
    sanoid_version: "{{ sanoid_version | default(default_value, true) }}"
