---
- name: Fail if Operating System is not Supported
  fail:
    msg: "Supported Operating System is Debian 64-bit"
  when:
    - ansible_distribution != 'Debian'
    - ansible_architecture != 'x86_64'

- name: Set Fact for 'node_ip'
  set_fact:
    node_ip: "{{ node_ip | default(default_value, true) }}"
