---
- name: Install Networking Tools Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    state: present
  with_items:
    - dnsutils
    - net-tools
    - traceroute
    - telnet
    - netcat
    - conntrack
    - iptables
    - bridge-utils
