---
- name: Install Disk Tools Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    install_recommends: no
    state: present
  with_items:
    - xfsprogs
    - fdisk
    - gdisk
    - parted
    - lvm2
