---
- name: Create Operating System Repository File
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Upgrade Operating System
  apt:
    force_apt_get: yes
    update_cache: yes
    dpkg_options: "force-confdef,force-confold"
    upgrade: full
  register: os_upgrade_info

- name: Restart Node If Operating System Upgraded
  shell: sleep 5 && shutdown -r now "Operating System Upgrade Triggered" 
  args:
    warn: false
  async: 1
  poll: 0    
  when:
    - os_upgrade_info.changed
    - reboot_upgrade == 'true'

- name: Wait For Node to Be Ready If Operating System Upgraded
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 600
  when: os_upgrade_info.changed

# - name: Enable Backports Repository
#   template:
#     src: backports.list.j2
#     dest: /etc/apt/sources.list.d/backports.list
#     owner: root
#     group: root
#     mode: 0644

- name: Install Base Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    state: present
  with_items:
    - lsb-release
    - bash-completion
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - dirmngr
    - gnupg
    - curl
    - wget
    - rsync
    - logrotate
    - byobu
