---
- name: Install Archiver Tools Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    state: present
  with_items:
    - tar
    - gzip
    - bzip2
    - xz-utils
    - p7zip-full
    - zip
    - unzip
