---
- name: Fail if Operating System is not Supported
  fail:
    msg: "Supported Operating System is Debian"
  when:
    - ansible_distribution != 'Debian'

- name: Set Facts
  set_fact:
    node_ip: "{{ node_ip | default(default_value, true) }}"
    node_name: "{{ node_name | default(default_value, true) }}"
    channel: "{{ channel | default(default_value, true) }}"
    version: "{{ version | default(default_value, true) }}"
    token: "{{ token | default(default_value, true) }}"
    db_host: "{{ db_host | default(default_value, true) }}"
    db_user: "{{ db_user | default(default_value, true) }}"
    db_password: "{{ db_password | default(default_value, true) }}"
    db_name: "{{ db_name | default(default_value, true) }}"
    enable_ip_vs: "{{ enable_ip_vs | default(default_value, true) }}"
    enable_zfs: "{{ enable_zfs | default(default_value, true) }}"
